[package]
name = "tilt-game"
version = "0.1.0"
edition = "2021"
authors = ["AD4MANTIS"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
config = "0.13.4"
console = "0.15.7"
directories = "5.0.1"
include_dir = "0.7.3"
num-derive = "0.4.1"
num-traits = "0.2.17"
once_cell = "1.19.0"
paste = "1.0.14"
ron = "0.8.1"
serde = { version = "1.0.193", features = ["derive"] }
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.51"
