[package]
name = "game-classes"
authors.workspace = true
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
maps.workspace = true
classes.workspace = true

console.workspace = true
serde.workspace = true

