[package]
name = "maps"

edition.workspace = true
version.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
classes.workspace = true

serde.workspace = true
thiserror.workspace = true
bevy_math.workspace = true
